// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package userlikeemailornamefinder

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserLikeEmailOrNameFinder is an autogenerated mock type for the UserLikeEmailOrNameFinder type
type MockUserLikeEmailOrNameFinder struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, req
func (_m *MockUserLikeEmailOrNameFinder) Run(ctx context.Context, req *UserLikeEmailOrNameFinderRequest) (*UserLikeEmailOrNameFinderResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *UserLikeEmailOrNameFinderResponse
	if rf, ok := ret.Get(0).(func(context.Context, *UserLikeEmailOrNameFinderRequest) *UserLikeEmailOrNameFinderResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UserLikeEmailOrNameFinderResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *UserLikeEmailOrNameFinderRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
