[tool]
[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
tag_format = "v$version"
version_files = [
  ".cz.toml:version"
]
bump_message = "release $current_version -> $new_version [skip-ci]"
