services:
    health_records_db:
        container_name: health_records_db_dev
        image: postgres
        ports:
            - "3456:5432"
        environment:
            - "POSTGRES_USER=development"
            - "POSTGRES_PASSWORD=development"
            - "POSTGRES_DB=health_records_db_dev"
        volumes:
            - "health_records_db_dev_vol:/var/lib/postgresql/data"
        restart: always
        networks:
            - health_records_dev_net
volumes:
    health_records_db_dev_vol:
networks:
    health_records_dev_net:
