// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package userfilters

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserByUUIDFinder is an autogenerated mock type for the UserByUUIDFinder type
type MockUserByUUIDFinder struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, req
func (_m *MockUserByUUIDFinder) Run(ctx context.Context, req *UserByUUIDFinderRequest) (*UserByUUIDFinderResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *UserByUUIDFinderResponse
	if rf, ok := ret.Get(0).(func(context.Context, *UserByUUIDFinderRequest) *UserByUUIDFinderResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UserByUUIDFinderResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *UserByUUIDFinderRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
