// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package validators

import mock "github.com/stretchr/testify/mock"

// MockValidatorService is an autogenerated mock type for the ValidatorService type
type MockValidatorService struct {
	mock.Mock
}

// Validate provides a mock function with given fields: e
func (_m *MockValidatorService) Validate(e interface{}) ValidateOutput {
	ret := _m.Called(e)

	var r0 ValidateOutput
	if rf, ok := ret.Get(0).(func(interface{}) ValidateOutput); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Get(0).(ValidateOutput)
	}

	return r0
}
