// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package biotestbyuuid

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockBiotestByUUID is an autogenerated mock type for the BiotestByUUID type
type MockBiotestByUUID struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, req
func (_m *MockBiotestByUUID) Run(ctx context.Context, req *BiotestByUUIDRequest) (*BiotestByUUIDResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *BiotestByUUIDResponse
	if rf, ok := ret.Get(0).(func(context.Context, *BiotestByUUIDRequest) *BiotestByUUIDResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*BiotestByUUIDResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *BiotestByUUIDRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
