// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package services

import mock "github.com/stretchr/testify/mock"

// MockUUIDGenerator is an autogenerated mock type for the UUIDGenerator type
type MockUUIDGenerator struct {
	mock.Mock
}

// New provides a mock function with given fields:
func (_m *MockUUIDGenerator) New() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
