// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"

	userfilters "github.com/manicar2093/charly_team_api/internal/userfilters"
	mock "github.com/stretchr/testify/mock"
)

// AllUsersFinder is an autogenerated mock type for the AllUsersFinder type
type AllUsersFinder struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, req
func (_m *AllUsersFinder) Run(ctx context.Context, req *userfilters.AllUsersFinderRequest) (*userfilters.AllUsersFinderResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *userfilters.AllUsersFinderResponse
	if rf, ok := ret.Get(0).(func(context.Context, *userfilters.AllUsersFinderRequest) *userfilters.AllUsersFinderResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userfilters.AllUsersFinderResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *userfilters.AllUsersFinderRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
