// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"

	biotest "github.com/manicar2093/charly_team_api/internal/biotest"

	mock "github.com/stretchr/testify/mock"
)

// BiotestImagesSaver is an autogenerated mock type for the BiotestImagesSaver type
type BiotestImagesSaver struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, biotestImages
func (_m *BiotestImagesSaver) Run(ctx context.Context, biotestImages *biotest.BiotestImagesSaverRequest) (*biotest.BiotestImagesSaverResponse, error) {
	ret := _m.Called(ctx, biotestImages)

	var r0 *biotest.BiotestImagesSaverResponse
	if rf, ok := ret.Get(0).(func(context.Context, *biotest.BiotestImagesSaverRequest) *biotest.BiotestImagesSaverResponse); ok {
		r0 = rf(ctx, biotestImages)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*biotest.BiotestImagesSaverResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *biotest.BiotestImagesSaverRequest) error); ok {
		r1 = rf(ctx, biotestImages)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
