// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"

	biotestfilters "github.com/manicar2093/health_records/internal/biotestfilters"

	mock "github.com/stretchr/testify/mock"
)

// BiotestByUUID is an autogenerated mock type for the BiotestByUUID type
type BiotestByUUID struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, req
func (_m *BiotestByUUID) Run(ctx context.Context, req *biotestfilters.BiotestByUUIDRequest) (*biotestfilters.BiotestByUUIDResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *biotestfilters.BiotestByUUIDResponse
	if rf, ok := ret.Get(0).(func(context.Context, *biotestfilters.BiotestByUUIDRequest) *biotestfilters.BiotestByUUIDResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*biotestfilters.BiotestByUUIDResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *biotestfilters.BiotestByUUIDRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
