// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"

	biotestfilters "github.com/manicar2093/charly_team_api/internal/biotestfilters"

	mock "github.com/stretchr/testify/mock"
)

// BiotestComparitionDataFinder is an autogenerated mock type for the BiotestComparitionDataFinder type
type BiotestComparitionDataFinder struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, req
func (_m *BiotestComparitionDataFinder) Run(ctx context.Context, req *biotestfilters.BiotestComparitionDataFinderRequest) (*biotestfilters.BiotestComparitionDataFinderResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *biotestfilters.BiotestComparitionDataFinderResponse
	if rf, ok := ret.Get(0).(func(context.Context, *biotestfilters.BiotestComparitionDataFinderRequest) *biotestfilters.BiotestComparitionDataFinderResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*biotestfilters.BiotestComparitionDataFinderResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *biotestfilters.BiotestComparitionDataFinderRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
