// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"

	biotest "github.com/manicar2093/health_records/internal/biotest"

	entities "github.com/manicar2093/health_records/internal/db/entities"

	mock "github.com/stretchr/testify/mock"
)

// BiotestCreator is an autogenerated mock type for the BiotestCreator type
type BiotestCreator struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, req
func (_m *BiotestCreator) Run(ctx context.Context, req *entities.Biotest) (*biotest.BiotestCreatorResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *biotest.BiotestCreatorResponse
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Biotest) *biotest.BiotestCreatorResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*biotest.BiotestCreatorResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *entities.Biotest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
