// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"

	catalog "github.com/manicar2093/charly_team_api/internal/catalog"

	mock "github.com/stretchr/testify/mock"
)

// CatalogGetter is an autogenerated mock type for the CatalogGetter type
type CatalogGetter struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, catalogs
func (_m *CatalogGetter) Run(ctx context.Context, catalogs *catalog.CatalogGetterRequest) (*catalog.CatalogGetterResponse, error) {
	ret := _m.Called(ctx, catalogs)

	var r0 *catalog.CatalogGetterResponse
	if rf, ok := ret.Get(0).(func(context.Context, *catalog.CatalogGetterRequest) *catalog.CatalogGetterResponse); ok {
		r0 = rf(ctx, catalogs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*catalog.CatalogGetterResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *catalog.CatalogGetterRequest) error); ok {
		r1 = rf(ctx, catalogs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
