// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CatalogRepository is an autogenerated mock type for the CatalogRepository type
type CatalogRepository struct {
	mock.Mock
}

// FindAllCatalogItems provides a mock function with given fields: _a0, _a1
func (_m *CatalogRepository) FindAllCatalogItems(_a0 context.Context, _a1 interface{}) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
