// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	filters "github.com/manicar2093/charly_team_api/db/filters"
	mock "github.com/stretchr/testify/mock"
)

// FilterService is an autogenerated mock type for the FilterService type
type FilterService struct {
	mock.Mock
}

// GetFilter provides a mock function with given fields: _a0
func (_m *FilterService) GetFilter(_a0 string) filters.FilterRunable {
	ret := _m.Called(_a0)

	var r0 filters.FilterRunable
	if rf, ok := ret.Get(0).(func(string) filters.FilterRunable); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(filters.FilterRunable)
		}
	}

	return r0
}
