// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TokenCreateable is an autogenerated mock type for the TokenCreateable type
type TokenCreateable struct {
	mock.Mock
}

// Gen provides a mock function with given fields: claims
func (_m *TokenCreateable) Gen(claims map[string]interface{}) (string, error) {
	ret := _m.Called(claims)

	var r0 string
	if rf, ok := ret.Get(0).(func(map[string]interface{}) string); ok {
		r0 = rf(claims)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(map[string]interface{}) error); ok {
		r1 = rf(claims)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
