// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"

	token "github.com/manicar2093/charly_team_api/internal/token"
	mock "github.com/stretchr/testify/mock"
)

// TokenClaimsGenerator is an autogenerated mock type for the TokenClaimsGenerator type
type TokenClaimsGenerator struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, req
func (_m *TokenClaimsGenerator) Run(ctx context.Context, req *token.TokenClaimsGeneratorRequest) (*token.TokenClaimsGeneratorResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *token.TokenClaimsGeneratorResponse
	if rf, ok := ret.Get(0).(func(context.Context, *token.TokenClaimsGeneratorRequest) *token.TokenClaimsGeneratorResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token.TokenClaimsGeneratorResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *token.TokenClaimsGeneratorRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
