// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TransformableToStruct is an autogenerated mock type for the TransformableToStruct type
type TransformableToStruct struct {
	mock.Mock
}

// Transform provides a mock function with given fields: data, holder
func (_m *TransformableToStruct) Transform(data *map[string]interface{}, holder interface{}) error {
	ret := _m.Called(data, holder)

	var r0 error
	if rf, ok := ret.Get(0).(func(*map[string]interface{}, interface{}) error); ok {
		r0 = rf(data, holder)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
