// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"

	user "github.com/manicar2093/charly_team_api/internal/user"
	mock "github.com/stretchr/testify/mock"
)

// UserCreator is an autogenerated mock type for the UserCreator type
type UserCreator struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, _a1
func (_m *UserCreator) Run(ctx context.Context, _a1 *user.UserCreatorRequest) (*user.UserCreatorResponse, error) {
	ret := _m.Called(ctx, _a1)

	var r0 *user.UserCreatorResponse
	if rf, ok := ret.Get(0).(func(context.Context, *user.UserCreatorRequest) *user.UserCreatorResponse); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserCreatorResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *user.UserCreatorRequest) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
