// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"

	userfilters "github.com/manicar2093/charly_team_api/internal/userfilters"
	mock "github.com/stretchr/testify/mock"
)

// UserLikeEmailOrNameFinder is an autogenerated mock type for the UserLikeEmailOrNameFinder type
type UserLikeEmailOrNameFinder struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, req
func (_m *UserLikeEmailOrNameFinder) Run(ctx context.Context, req *userfilters.UserLikeEmailOrNameFinderRequest) (*userfilters.UserLikeEmailOrNameFinderResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *userfilters.UserLikeEmailOrNameFinderResponse
	if rf, ok := ret.Get(0).(func(context.Context, *userfilters.UserLikeEmailOrNameFinderRequest) *userfilters.UserLikeEmailOrNameFinderResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userfilters.UserLikeEmailOrNameFinderResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *userfilters.UserLikeEmailOrNameFinderRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
