// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"

	userfilters "github.com/manicar2093/health_records/internal/userfilters"
	mock "github.com/stretchr/testify/mock"
)

// UserByUUIDFinder is an autogenerated mock type for the UserByUUIDFinder type
type UserByUUIDFinder struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, req
func (_m *UserByUUIDFinder) Run(ctx context.Context, req *userfilters.UserByUUIDFinderRequest) (*userfilters.UserByUUIDFinderResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *userfilters.UserByUUIDFinderResponse
	if rf, ok := ret.Get(0).(func(context.Context, *userfilters.UserByUUIDFinderRequest) *userfilters.UserByUUIDFinderResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userfilters.UserByUUIDFinderResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *userfilters.UserByUUIDFinderRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
