// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/manicar2093/health_records/internal/db/entities"
	mock "github.com/stretchr/testify/mock"

	user "github.com/manicar2093/health_records/internal/user"
)

// UserUpdater is an autogenerated mock type for the UserUpdater type
type UserUpdater struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, userData
func (_m *UserUpdater) Run(ctx context.Context, userData *entities.User) (*user.UserUpdaterResponse, error) {
	ret := _m.Called(ctx, userData)

	var r0 *user.UserUpdaterResponse
	if rf, ok := ret.Get(0).(func(context.Context, *entities.User) *user.UserUpdaterResponse); ok {
		r0 = rf(ctx, userData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserUpdaterResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *entities.User) error); ok {
		r1 = rf(ctx, userData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
