// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UUIDValidator is an autogenerated mock type for the UUIDValidator type
type UUIDValidator struct {
	mock.Mock
}

// ValidateUUID provides a mock function with given fields: value
func (_m *UUIDValidator) ValidateUUID(value string) bool {
	ret := _m.Called(value)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(value)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
