// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package biotestsbyuseruuidfinder

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockBiotestByUserUUID is an autogenerated mock type for the BiotestByUserUUID type
type MockBiotestByUserUUID struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, req
func (_m *MockBiotestByUserUUID) Run(ctx context.Context, req *BiotestByUserUUIDRequest) (*BiotestByUserUUIDResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *BiotestByUserUUIDResponse
	if rf, ok := ret.Get(0).(func(context.Context, *BiotestByUserUUIDRequest) *BiotestByUserUUIDResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*BiotestByUserUUIDResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *BiotestByUserUUIDRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
