// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package services

import mock "github.com/stretchr/testify/mock"

// MockPassGen is an autogenerated mock type for the PassGen type
type MockPassGen struct {
	mock.Mock
}

// Generate provides a mock function with given fields:
func (_m *MockPassGen) Generate() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
