// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package catalog

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCatalogGetter is an autogenerated mock type for the CatalogGetter type
type MockCatalogGetter struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, catalogs
func (_m *MockCatalogGetter) Run(ctx context.Context, catalogs *CatalogGetterRequest) (*CatalogGetterResponse, error) {
	ret := _m.Called(ctx, catalogs)

	var r0 *CatalogGetterResponse
	if rf, ok := ret.Get(0).(func(context.Context, *CatalogGetterRequest) *CatalogGetterResponse); ok {
		r0 = rf(ctx, catalogs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CatalogGetterResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *CatalogGetterRequest) error); ok {
		r1 = rf(ctx, catalogs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
