// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package biotestcreator

import (
	context "context"

	entities "github.com/manicar2093/charly_team_api/internal/db/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockBiotestCreator is an autogenerated mock type for the BiotestCreator type
type MockBiotestCreator struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, req
func (_m *MockBiotestCreator) Run(ctx context.Context, req *entities.Biotest) (*BiotestCreatorResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *BiotestCreatorResponse
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Biotest) *BiotestCreatorResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*BiotestCreatorResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *entities.Biotest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
