// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package user

import (
	context "context"

	entities "github.com/manicar2093/charly_team_api/internal/db/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockUserUpdater is an autogenerated mock type for the UserUpdater type
type MockUserUpdater struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, userData
func (_m *MockUserUpdater) Run(ctx context.Context, userData *entities.User) (*UserUpdaterResponse, error) {
	ret := _m.Called(ctx, userData)

	var r0 *UserUpdaterResponse
	if rf, ok := ret.Get(0).(func(context.Context, *entities.User) *UserUpdaterResponse); ok {
		r0 = rf(ctx, userData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UserUpdaterResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *entities.User) error); ok {
		r1 = rf(ctx, userData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
