// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package user

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAvatarUpdater is an autogenerated mock type for the AvatarUpdater type
type MockAvatarUpdater struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, req
func (_m *MockAvatarUpdater) Run(ctx context.Context, req *AvatarUpdaterRequest) (*AvatarUpdaterResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *AvatarUpdaterResponse
	if rf, ok := ret.Get(0).(func(context.Context, *AvatarUpdaterRequest) *AvatarUpdaterResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AvatarUpdaterResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *AvatarUpdaterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
