// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package allusersfinder

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAllUsersFinder is an autogenerated mock type for the AllUsersFinder type
type MockAllUsersFinder struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, req
func (_m *MockAllUsersFinder) Run(ctx context.Context, req *AllUsersFinderRequest) (*AllUsersFinderResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *AllUsersFinderResponse
	if rf, ok := ret.Get(0).(func(context.Context, *AllUsersFinderRequest) *AllUsersFinderResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AllUsersFinderResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *AllUsersFinderRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
