// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package repositories

import (
	context "context"

	entities "github.com/manicar2093/charly_team_api/db/entities"
	mock "github.com/stretchr/testify/mock"

	paginator "github.com/manicar2093/charly_team_api/db/paginator"
)

// MockBiotestRepository is an autogenerated mock type for the BiotestRepository type
type MockBiotestRepository struct {
	mock.Mock
}

// FindBiotestByUUID provides a mock function with given fields: ctx, biotestUUID
func (_m *MockBiotestRepository) FindBiotestByUUID(ctx context.Context, biotestUUID string) (*entities.Biotest, error) {
	ret := _m.Called(ctx, biotestUUID)

	var r0 *entities.Biotest
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Biotest); ok {
		r0 = rf(ctx, biotestUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Biotest)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, biotestUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllUserBiotestByUserUUID provides a mock function with given fields: ctx, pageSort, userUUID
func (_m *MockBiotestRepository) GetAllUserBiotestByUserUUID(ctx context.Context, pageSort *paginator.PageSort, userUUID string) (*paginator.Paginator, error) {
	ret := _m.Called(ctx, pageSort, userUUID)

	var r0 *paginator.Paginator
	if rf, ok := ret.Get(0).(func(context.Context, *paginator.PageSort, string) *paginator.Paginator); ok {
		r0 = rf(ctx, pageSort, userUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paginator.Paginator)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *paginator.PageSort, string) error); ok {
		r1 = rf(ctx, pageSort, userUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllUserBiotestByUserUUIDAsCatalog provides a mock function with given fields: ctx, pageSort, userUUID
func (_m *MockBiotestRepository) GetAllUserBiotestByUserUUIDAsCatalog(ctx context.Context, pageSort *paginator.PageSort, userUUID string) (*paginator.Paginator, error) {
	ret := _m.Called(ctx, pageSort, userUUID)

	var r0 *paginator.Paginator
	if rf, ok := ret.Get(0).(func(context.Context, *paginator.PageSort, string) *paginator.Paginator); ok {
		r0 = rf(ctx, pageSort, userUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paginator.Paginator)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *paginator.PageSort, string) error); ok {
		r1 = rf(ctx, pageSort, userUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetComparitionDataByUserUUID provides a mock function with given fields: ctx, userUUID
func (_m *MockBiotestRepository) GetComparitionDataByUserUUID(ctx context.Context, userUUID string) (*BiotestComparisionResponse, error) {
	ret := _m.Called(ctx, userUUID)

	var r0 *BiotestComparisionResponse
	if rf, ok := ret.Get(0).(func(context.Context, string) *BiotestComparisionResponse); ok {
		r0 = rf(ctx, userUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*BiotestComparisionResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveBiotest provides a mock function with given fields: ctx, biotest
func (_m *MockBiotestRepository) SaveBiotest(ctx context.Context, biotest *entities.Biotest) error {
	ret := _m.Called(ctx, biotest)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Biotest) error); ok {
		r0 = rf(ctx, biotest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBiotest provides a mock function with given fields: ctx, biotest
func (_m *MockBiotestRepository) UpdateBiotest(ctx context.Context, biotest *entities.Biotest) error {
	ret := _m.Called(ctx, biotest)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Biotest) error); ok {
		r0 = rf(ctx, biotest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
