// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package biotest

import (
	context "context"

	entities "github.com/manicar2093/charly_team_api/internal/db/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockBiotestUpdater is an autogenerated mock type for the BiotestUpdater type
type MockBiotestUpdater struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, req
func (_m *MockBiotestUpdater) Run(ctx context.Context, req *entities.Biotest) (*BiotestUpdaterResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *BiotestUpdaterResponse
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Biotest) *BiotestUpdaterResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*BiotestUpdaterResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *entities.Biotest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
