name: Test project

on:
  pull_request:
    types: [edited, synchronize, opened, reopened]
    branches: [ main ]

jobs:

  test:
    name: Run Test
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        os: [ ubuntu-latest ]
        node-version: [ 14.16.x ]
    runs-on: ${{ matrix.os }}
    env:
        DB_URL: ${{ secrets.DB_URL_TEST }}

    services:
      postgres:
        image: postgres
        ports:
          - 3456:5432
        env:
          POSTGRES_USER: ${{ secrets.DB_USER_TEST }}testing
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD_TEST }}
          POSTGRES_DB: ${{ secrets.DB_NAME_TEST }}

    steps:
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Set up NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: go mod download

    - name: Install Knex
      run: npm install -g knex

    - name: Install Node dependencies
      run: npm install

    - name: Migrate DB
      run: make db_testing_fill
      
    - name: Test
      run: go test ./... -v
    
    - name: Rollback to DB
      run: make db_testing_rollback
