// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package biotestimagessaver

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockBiotestImagesSaver is an autogenerated mock type for the BiotestImagesSaver type
type MockBiotestImagesSaver struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, biotestImages
func (_m *MockBiotestImagesSaver) Run(ctx context.Context, biotestImages *BiotestImagesSaverRequest) (*BiotestImagesSaverResponse, error) {
	ret := _m.Called(ctx, biotestImages)

	var r0 *BiotestImagesSaverResponse
	if rf, ok := ret.Get(0).(func(context.Context, *BiotestImagesSaverRequest) *BiotestImagesSaverResponse); ok {
		r0 = rf(ctx, biotestImages)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*BiotestImagesSaverResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *BiotestImagesSaverRequest) error); ok {
		r1 = rf(ctx, biotestImages)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
