// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package filters

import mock "github.com/stretchr/testify/mock"

// MockFilterFunc is an autogenerated mock type for the FilterFunc type
type MockFilterFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: filterParameters
func (_m *MockFilterFunc) Execute(filterParameters *FilterParameters) (interface{}, error) {
	ret := _m.Called(filterParameters)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(*FilterParameters) interface{}); ok {
		r0 = rf(filterParameters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*FilterParameters) error); ok {
		r1 = rf(filterParameters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
